name: Streamlining-Website-Deployment-through-AWS-CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync Website Deployment to S3 bucket
        run: |
          aws s3 cp index.html http://hosting-static-website-using-github-action.s3-website-us-east-1.amazonaws.com
